### ISSUE TITLE
Version 5.0.2 missing index.js

### ISSUE THREAD

**Issue by MattCheely** [rtfeldman/node-elm-compiler#94]
It looks like v5.0.2 was published to npm without compiling the typescript. After `npm install node-elm-compiler`:

```
▶ tree node_modules/node-elm-compiler                                                   
node_modules/node-elm-compiler
├── appveyor.yml
├── examples
│   ├── compileHelloWorld.js
│   ├── elm.json
│   └── HelloWorld.elm
├── LICENSE
├── package.json
└── README.md

1 directory, 7 files
```

**Comment by rtfeldman** [comment]
Huh! I guess we don't have a prepublish script set up for that.

Anyone who knows TS better than I do want to PR that? 😅

**Comment by MattCheely** [comment]
At a glance, it looks like the [prepack script](https://docs.npmjs.com/misc/scripts) in [package.json](https://github.com/rtfeldman/node-elm-compiler/blob/master/package.json#L7) should have done the job.

**Comment by Hermanverschooten** [comment]
Is this the reason I am getting `Error: Cannot find module 'node-elm-compiler` in `elm-webpack-loader` after upgrading to 5.0.2?

**Comment by Syllogie** [comment]
@Hermanverschoo : Yes.   `npm install node-elm-compiler@5.0.1` fixes said Error for me.

**Comment by rtfeldman** [comment]
ok, try 5.0.3 - should be fixed now!

**Comment by MattCheely** [comment]
5.0.3 works!
